const questoes = [
  {
    "tema": "NR 101",
    "pergunta": "De acordo com os excertos que abordam a Norma Regulamentadora nº 10 (NR 10), qual é o objetivo principal desta norma?",
    "alternativa1": "Garantir a gestão da integridade estrutural de caldeiras e vasos de pressão.",
    "alternativa2": "Estabelecer requisitos mínimos para a gestão de riscos psicossociais no trabalho.",
    "alternativa3": "Definir as referências técnicas e medidas de proteção para trabalhos em altura.",
    "alternativa4": "Estabelecer requisitos e condições mínimas para garantir a segurança e saúde dos trabalhadores que interagem com instalações e serviços em eletricidade.",
    "alternativa5": "Regulamentar as atividades de agricultura, pecuária, silvicultura, exploração florestal e aquicultura.",
    "respostaCorreta": "D",
    "gabaritoComentado": "O excerto e indicam que a NR 10 define as referências técnicas, os princípios fundamentais e as medidas de proteção para resguardar a saúde e a integridade física dos trabalhadores em atividades que envolvam máquinas e equipamentos, com foco específico, no contexto apresentado, em segurança em eletricidade. A alternativa D alinha-se a este objetivo, focando na segurança e saúde dos trabalhadores que interagem com instalações e serviços em eletricidade."
  },
  {
    "tema": "NR 10",
    "pergunta": "Considerando as informações apresentadas nos excertos sobre acidentes de trabalho relacionados à eletricidade, qual percentual de subnotificação é estimado para esses acidentes no setor formal?",
    "alternativa1": "Aproximadamente 20%",
    "alternativa2": "Aproximadamente 40%",
    "alternativa3": "Aproximadamente 60%",
    "alternativa4": "Aproximadamente 80%",
    "alternativa5": "Aproximadamente 90%",
    "respostaCorreta": "D",
    "gabaritoComentado": "O excerto menciona que 'estudos estimam que o percentual de subnotificação é de cerca de 80%, isto é, de cada 10 acidentes, apenas 2 são reportados'."
  },
  {
    "tema": "NR 10",
    "pergunta": "Conforme os excertos, que tratam, entre outros temas, da NR 10, qual das opções a seguir NÃO é mencionada como um tipo de acidente para o qual muitos acidentes elétricos são reportados, contribuindo para a subnotificação?",
    "alternativa1": "Quedas.",
    "alternativa2": "Queimaduras.",
    "alternativa3": "Intoxicações.",
    "alternativa4": "Nenhuma das alternativas anteriores, pois quedas e queimaduras são expressamente mencionadas.",
    "alternativa5": "Ambas, quedas e queimaduras.",
    "respostaCorreta": "C",
    "gabaritoComentado": "O excerto afirma que 'muitos acidentes decorrentes do perigo da energia elétrica são reportados como sendo oriundos de quedas e queimaduras'. Intoxicações não são mencionadas neste contexto."
  },
  {
    "tema": "NR 10",
    "pergunta": "Nos excertos, a Análise Preliminar de Risco (APR) é apresentada como uma técnica de:",
    "alternativa1": "Gerenciamento de emergências.",
    "alternativa2": "Avaliação de desempenho de equipamentos.",
    "alternativa3": "Análise de risco.",
    "alternativa4": "Planejamento financeiro.",
    "alternativa5": "Controle de qualidade de processos.",
    "respostaCorreta": "C",
    "gabaritoComentado": "A figura 4 no excerto e sua referência no excerto identificam a APR como um 'Exemplo de uma técnica de análise de risco'."
  },
  {
    "tema": "NR 10",
    "pergunta": "De acordo com o excerto, que lista os documentos que compõem o Prontuário da NR 10, qual dos seguintes itens DEVE constar neste conjunto de documentos?",
    "alternativa1": "Relatórios de análise de acidentes e doenças relacionadas ao trabalho.",
    "alternativa2": "As especificações técnicas dos Equipamentos de Proteção Coletiva e Individual (EPC e EPI) e o ferramental utilizado.",
    "alternativa3": "O planejamento anual das inspeções de segurança das instalações.",
    "alternativa4": "O registro de entrega de Equipamentos de Proteção Individual (EPIs).",
    "alternativa5": "O mapa de risco da área de instalações elétricas.",
    "respostaCorreta": "B",
    "gabaritoComentado": "O excerto lista a 'especificação dos equipamentos de proteção coletiva e individual e o ferramental' como um dos documentos que compõem o Prontuário. As alternativas A, C, E não são explicitamente listadas em. A alternativa D, embora o registro de fornecimento de EPI seja importante, o excerto lista a 'especificação' dos EPIs e ferramental, não o registro individual de entrega."
  },
  {
    "tema": "NR 10",
    "pergunta": "Conforme descrito no excerto, o Prontuário de Instalações Elétricas, no contexto da NR 10, constitui um(a):",
    "alternativa1": "Relatório único consolidado.",
    "alternativa2": "Sistema informatizado de gestão.",
    "alternativa3": "Plano de ação detalhado.",
    "alternativa4": "Conjunto de documentos.",
    "alternativa5": "Certificado de conformidade.",
    "respostaCorreta": "D",
    "gabaritoComentado": "O excerto inicia sua descrição do Prontuário afirmando: 'O Prontuário é um conjunto de documentos...'"
  },
  {
    "tema": "NR 10",
    "pergunta": "Segundo o excerto, os procedimentos de trabalho relacionados à NR 10 devem conter, no mínimo, uma série de informações. Qual das opções abaixo NÃO faz parte do conteúdo mínimo exigido para esses procedimentos?",
    "alternativa1": "Objetivo.",
    "alternativa2": "Campo de aplicação.",
    "alternativa3": "Resultados esperados.",
    "alternativa4": "Medidas de controle.",
    "alternativa5": "Disposições gerais.",
    "respostaCorreta": "C",
    "gabaritoComentado": "O excerto lista o conteúdo mínimo dos procedimentos de trabalho: 'objetivo, campo de aplicação, base técnica, competências e responsabilidades, disposições gerais, medidas de controle e orientações finais'. 'Resultados esperados' não consta nesta lista."
  },
  {
    "tema": "NR 10",
    "pergunta": "Considerando o modelo de Análise Preliminar de Risco (APR) apresentado nos excertos e, qual dos seguintes campos ou seções NÃO aparece no formulário?",
    "alternativa1": "Equipamento / Máquina / Instalação.",
    "alternativa2": "Gerência de Área.",
    "alternativa3": "Histórico de Acidentes Anteriores.",
    "alternativa4": "Telefones Úteis.",
    "alternativa5": "Descrição da Atividade.",
    "respostaCorreta": "C",
    "gabaritoComentado": "O modelo de APR mostrado nos excertos e inclui campos como 'Equipamento / Máquina / Instalação', 'Gerência de Área', 'Telefones Úteis', e 'Descrição da Atividade'. Não há um campo específico para 'Histórico de Acidentes Anteriores' no modelo exibido."
  },
  {
    "tema": "NR 10",
    "pergunta": "Ainda sobre o modelo de Análise Preliminar de Risco (APR) presente nos excertos, na seção 'TREINAMENTO DE SEGURANÇA DA APR', são previstos campos para registro de:",
    "alternativa1": "Carga horária e conteúdo programático.",
    "alternativa2": "Avaliação de eficácia do treinamento.",
    "alternativa3": "RE, Função e Assinatura.",
    "alternativa4": "Nome do instrutor e entidade promotora.",
    "alternativa5": "Data de validade do treinamento.",
    "respostaCorreta": "C",
    "gabaritoComentado": "A seção 'TREINAMENTO DE SEGURANÇA DA APR' no excerto apresenta colunas para 'RE', 'FUNÇÃO', e 'ASSINATURA', indicando o registro da participação dos trabalhadores neste treinamento específico da APR."
  },
  {
    "tema": "NR 10",
    "pergunta": "Além dos procedimentos e instruções de segurança e saúde, o Prontuário da NR 10 deve incluir, conforme o excerto, a documentação dos testes realizados em quais elementos das instalações elétricas?",
    "alternativa1": "Testes de continuidade de circuitos.",
    "alternativa2": "Testes de funcionamento de disjuntores.",
    "alternativa3": "Testes de isolação elétrica.",
    "alternativa4": "Testes de carga em transformadores.",
    "alternativa5": "Testes de resistência de componentes.",
    "respostaCorreta": "C",
    "gabaritoComentado": "O excerto especifica que o Prontuário deve conter a 'documentação dos resultados dos testes de isolação elétrica realizados'."
  },
  {
    "tema": "NR 10",
    "pergunta": "No que diz respeito à documentação dos trabalhadores no Prontuário da NR 10, o excerto indica que deve ser incluída a documentação comprobatória de:",
    "alternativa1": "Exames médicos periódicos.",
    "alternativa2": "Histórico profissional.",
    "alternativa3": "Qualificação, habilitação, capacitação e autorização dos trabalhadores e dos treinamentos realizados.",
    "alternativa4": "Participação em comissões internas de prevenção de acidentes (CIPA).",
    "alternativa5": "Registro em conselho de classe profissional.",
    "respostaCorreta": "C",
    "gabaritoComentado": "O excerto lista, entre os documentos que compõem o Prontuário, a 'documentação comprobatória da qualificação, habilitação, capacitação, autorização dos trabalhadores e dos treinamentos realizados'."
  },
  {
    "tema": "NR 10",
    "pergunta": "A Análise Preliminar de Risco (APR), conforme o modelo apresentado no excerto, inclui no campo 'SITUAÇÃO' diversas opções para indicar o contexto da atividade. Quais das seguintes opções estão listadas?",
    "alternativa1": "Emergência, Rotina, Planejada.",
    "alternativa2": "Instalação, Manutenção, Inspeção.",
    "alternativa3": "Parada Programada, Fora de Parada, Parada Acidental.",
    "alternativa4": "Alta Tensão, Baixa Tensão, Média Tensão.",
    "alternativa5": "Diurna, Noturna, Fim de Semana.",
    "respostaCorreta": "C",
    "gabaritoComentado": "No modelo de APR apresentado no excerto, o campo 'SITUAÇÃO' oferece as opções: 'Parada Programada', 'Fora de Parada', 'Parada Acidental', 'Atividade de Segurança', 'RE', e 'Obra Nova'. As alternativas A, B, D e E não correspondem às opções listadas neste campo do modelo."
  },
  {
    "tema": "NR 10",
    "pergunta": "De acordo com o excerto, qual dos itens abaixo é listado como parte do conteúdo mínimo que deve constar nos procedimentos de trabalho?",
    "alternativa1": "Base técnica.",
    "alternativa2": "Custos da atividade.",
    "alternativa3": "Prazo de execução.",
    "alternativa4": "Lista de materiais.",
    "alternativa5": "Previsão de orçamento.",
    "respostaCorreta": "A",
    "gabaritoComentado": "O excerto detalha o conteúdo mínimo dos procedimentos de trabalho, incluindo 'base técnica'. Os demais itens não são mencionados como obrigatórios nesta lista."
  },
  {
    "tema": "NR 10",
    "pergunta": "Qual dos seguintes documentos, listados no excerto, deve obrigatoriamente fazer parte do Prontuário das Instalações Elétricas?",
    "alternativa1": "O relatório de inspeção de segurança de caldeiras.",
    "alternativa2": "Os procedimentos de trabalho para atividades rotineiras e não rotineiras.",
    "alternativa3": "Os resultados de avaliação de desempenho dos trabalhadores.",
    "alternativa4": "O cronograma de manutenção preventiva das máquinas.",
    "alternativa5": "O atestado de saúde ocupacional (ASO) dos trabalhadores.",
    "respostaCorreta": "B",
    "gabaritoComentado": "O excerto afirma que o Prontuário inclui 'o conjunto de procedimentos e instruções técnicas e administrativas de segurança e saúde'. As alternativas A, C, D e E não correspondem a itens listados no excerto como parte do Prontuário da NR 10."
  },
  {
    "tema": "NR 10",
    "pergunta": "No contexto da Análise Preliminar de Risco (APR) apresentada, a seção 'HOUVE INCIDENTE DURANTE A ATIVIDADE?' sugere uma ação específica caso a resposta seja afirmativa. Qual é essa ação?",
    "alternativa1": "Registrar o incidente no campo 'Observações Finais'.",
    "alternativa2": "Realizar uma nova APR imediatamente.",
    "alternativa3": "Comunicar o incidente à chefia imediata.",
    "alternativa4": "Encaminhar para o Setor de Segurança do Trabalho.",
    "alternativa5": "Suspender a atividade e aguardar novas instruções.",
    "respostaCorreta": "D",
    "gabaritoComentado": "No excerto, na seção 'HOUVE INCIDENTE DURANTE A ATIVIDADE?', a instrução é: 'Se \"SIM\", encaminhar para Setor de Segurança do Trabalho'."
  },
  {
    "tema": "NR 10",
    "pergunta": "Considerando a lista de documentos que compõem o Prontuário da NR 10 no excerto, qual tipo de documentação referente a inspeções e medições é especificamente mencionada?",
    "alternativa1": "Inspeções de extintores de incêndio.",
    "alternativa2": "Inspeções e medições do sistema de proteção contra descargas atmosféricas e aterramentos elétricos.",
    "alternativa3": "Inspeções visuais das instalações elétricas.",
    "alternativa4": "Medições de níveis de ruído e vibração.",
    "alternativa5": "Inspeções de equipamentos de proteção individual (EPI).",
    "respostaCorreta": "B",
    "gabaritoComentado": "O excerto inclui no Prontuário a 'documentação das inspeções e medições do sistema de proteção contra descargas atmosféricas e aterramentos elétricos'."
  },
  {
    "tema": "NR 10",
    "pergunta": "No modelo de Análise Preliminar de Risco (APR) apresentado, qual campo é destinado à identificação da área responsável pela atividade?",
    "alternativa1": "LOCAL DE TRABALHO.",
    "alternativa2": "EQUIPAMENTO / MÁQUINA / INSTALAÇÃO.",
    "alternativa3": "GERÊNCIA DE ÁREA.",
    "alternativa4": "DESCRIÇÃO DA ATIVIDADE.",
    "alternativa5": "OBSERVAÇÕES FINAIS.",
    "respostaCorreta": "C",
    "gabaritoComentado": "O modelo de APR mostrado no excerto possui um campo específico denominado 'GERÊNCIA DE ÁREA'."
  },
  {
    "tema": "NR 10",
    "pergunta": "Os excertos mencionam que muitos acidentes decorrentes do perigo da energia elétrica são reportados de forma inadequada. Qual o principal impacto dessa prática, segundo os excertos?",
    "alternativa1": "Aumento do número total de acidentes registrados.",
    "alternativa2": "Dificulta a compreensão do universo real de acidentes elétricos.",
    "alternativa3": "Melhora as estatísticas de segurança em instalações elétricas.",
    "alternativa4": "Reduz a necessidade de investigações detalhadas.",
    "alternativa5": "Simplifica o processo de comunicação de acidentes.",
    "respostaCorreta": "B",
    "gabaritoComentado": "O excerto discute a subnotificação e o reporte inadequado (como quedas/queimaduras), concluindo que 'Desta forma, saliente-se que os números apresentados não representam todo o universo de acidentes'. Isso indica que a prática dificulta a compreensão da real dimensão dos acidentes elétricos."
  },
  {
    "tema": "NR 10",
    "pergunta": "Conforme o excerto, qual item referente ao contexto e alcance da atividade deve constar no conteúdo mínimo dos procedimentos de trabalho?",
    "alternativa1": "Competências e responsabilidades.",
    "alternativa2": "Base técnica.",
    "alternativa3": "Campo de aplicação.",
    "alternativa4": "Orientações finais.",
    "alternativa5": "Medidas de controle.",
    "respostaCorreta": "C",
    "gabaritoComentado": "O excerto lista 'campo de aplicação' como um dos itens do conteúdo mínimo dos procedimentos de trabalho. Este item se refere ao alcance ou contexto onde o procedimento deve ser aplicado."
  },
  {
    "tema": "NR 10",
    "pergunta": "Considerando o excerto, que trata do Prontuário da NR 10, qual tipo de documentação sobre os trabalhadores é explicitamente exigida?",
    "alternativa1": "Atestados de aptidão física.",
    "alternativa2": "Registros de jornada de trabalho.",
    "alternativa3": "Comprovação de qualificação, habilitação, capacitação, autorização e treinamentos.",
    "alternativa4": "Histórico de participação em simulados de emergência.",
    "alternativa5": "Comprovantes de escolaridade formal.",
    "respostaCorreta": "C",
    "gabaritoComentado": "O excerto lista como componente do Prontuário a 'documentação comprobatória da qualificação, habilitação, capacitação, autorização dos trabalhadores e dos treinamentos realizados'."
  },
  {
    "tema": "NR 10",
    "pergunta": "O excerto determina que os procedimentos de trabalho devem conter, no mínimo, as 'competências e responsabilidades'. Em qual contexto essa informação se aplica?",
    "alternativa1": "Definir as atribuições dos órgãos fiscalizadores.",
    "alternativa2": "Descrever as qualificações técnicas dos equipamentos.",
    "alternativa3": "Especificar quem são os responsáveis e quais as atribuições na execução do procedimento.",
    "alternativa4": "Determinar a responsabilidade civil em caso de acidentes.",
    "alternativa5": "Estabeler as responsabilidades do fabricante do equipamento.",
    "respostaCorreta": "C",
    "gabaritoComentado": "No contexto de um procedimento de trabalho, 'competências e responsabilidades' (excerto) refere-se tipicamente à definição de quem está apto a realizar as tarefas descritas e quais são as responsabilidades associadas a essas funções durante a execução do procedimento."
  },
  {
    "tema": "NR 10",
    "pergunta": "No modelo de Análise Preliminar de Risco (APR) apresentado, para que o campo 'DESCRIÇÃO DA ATIVIDADE' é utilizado?",
    "alternativa1": "Para listar os riscos identificados.",
    "alternativa2": "Para detalhar as medidas de controle.",
    "alternativa3": "Para registrar o passo a passo da tarefa a ser realizada.",
    "alternativa4": "Para indicar o local físico do trabalho.",
    "alternativa5": "Para identificar os trabalhadores envolvidos.",
    "respostaCorreta": "C",
    "gabaritoComentado": "O campo 'DESCRIÇÃO DA ATIVIDADE' em uma APR é onde se detalha a tarefa a ser executada, geralmente descrevendo as etapas do trabalho."
  },
  {
    "tema": "NR 10",
    "pergunta": "Os excertos indicam que acidentes de trabalho relacionados à eletricidade originam-se de Comunicações de Acidentes de Trabalho (CAT). Qual setor, segundo os excertos, é abrangido por essas CATs de origem?",
    "alternativa1": "Apenas o setor público.",
    "alternativa2": "Apenas o setor privado.",
    "alternativa3": "Ambos, setor público e privado.",
    "alternativa4": "Apenas o setor formal.",
    "alternativa5": "Apenas o setor informal.",
    "respostaCorreta": "D",
    "gabaritoComentado": "O excerto afirma que os acidentes de trabalho 'abrangem apenas o setor formal', referindo-se à origem dos dados de acidentes a partir das CATs."
  },
  {
    "tema": "NR 10",
    "pergunta": "Qual das seguintes opções representa um tipo de informação que DEVE constar no conteúdo mínimo dos procedimentos de trabalho, segundo o excerto?",
    "alternativa1": "Orientações finais.",
    "alternativa2": "Histórico de revisões.",
    "alternativa3": "Lista de verificação pré-uso.",
    "alternativa4": "Diagrama unifilar da instalação.",
    "alternativa5": "Planilha de avaliação de riscos.",
    "respostaCorreta": "A",
    "gabaritoComentado": "O excerto lista 'orientações finais' como um dos itens do conteúdo mínimo dos procedimentos de trabalho."
  },
  {
    "tema": "NR 10",
    "pergunta": "A definição de 'Profissional Habilitado', mencionada em excertos (geral) e (contexto NR 10 Prontuário), refere-se àquele que:",
    "alternativa1": "Comprove conclusão de curso específico e reconhecimento pelo sistema oficial de ensino.",
    "alternativa2": "Recebeu capacitação sob orientação e responsabilidade de profissional habilitado.",
    "alternativa3": "Possui comprovação de aptidão mediante exame clínico.",
    "alternativa4": "É trabalhador qualificado e recebeu autorização formal da empresa.",
    "alternativa5": "Possui graduação e registro no conselho de classe competente, se necessário, com atribuições legais.",
    "respostaCorreta": "E",
    "gabaritoComentado": "O excerto define 'Profissional Habilitado' como 'aquele que possui comprovação de conclusão de curso específico reconhecido pelo sistema oficial de ensino, com registro no competente conselho de classe, se necessário'. Complementarmente, outros excertos adicionam 'com atribuição compatível'. A alternativa E reflete essa definição completa."
  },
  {
    "tema": "NR 10",
    "pergunta": "O excerto estabelece que a especificação dos Equipamentos de Proteção Coletiva e Individual (EPC e EPI) e o ferramental devem constar no Prontuário. Qual a relevância dessa informação?",
    "alternativa1": "Identificar os fabricantes dos equipamentos.",
    "alternativa2": "Permitir a gestão do estoque de EPIs.",
    "alternativa3": "Garantir que os equipamentos e ferramentas utilizados são adequados e especificados para as atividades.",
    "alternativa4": "Facilitar o processo de compra de novos equipamentos.",
    "alternativa5": "Cumprir uma exigência documental sem impacto prático.",
    "respostaCorreta": "C",
    "gabaritoComentado": "Incluir a especificação de EPC, EPI e ferramental no Prontuário é fundamental para garantir que os meios de proteção e as ferramentas utilizadas nas instalações elétricas sejam apropriados para a segurança e saúde dos trabalhadores, conforme as necessidades das atividades."
  },
  {
    "tema": "NR 10",
    "pergunta": "No modelo de APR apresentado, o campo 'OM / Contrato nº' aparece em diferentes seções do formulário. Isso sugere que este dado é importante para:",
    "alternativa1": "Identificar o responsável pela aprovação da APR.",
    "alternativa2": "Vincular a APR a uma ordem de serviço ou contrato específico.",
    "alternativa3": "Registrar o número de trabalhadores envolvidos.",
    "alternativa4": "Indicar a data de validade da APR.",
    "alternativa5": "Classificar o grau de risco da atividade.",
    "respostaCorreta": "B",
    "gabaritoComentado": "O campo 'OM / Contrato nº' é um identificador comum em documentos de segurança do trabalho para associar a atividade ou análise a uma Ordem de Manutenção (OM) ou número de contrato específico, vinculando a APR ao trabalho que está sendo realizado."
  },
  {
    "tema": "NR 10",
    "pergunta": "Os excertos mencionam que a subnotificação de acidentes elétricos pode ocorrer. Qual é uma das consequências diretas dessa subnotificação, segundo as informações fornecidas?",
    "alternativa1": "Os números oficiais de acidentes refletem precisamente a realidade.",
    "alternativa2": "A percepção do risco elétrico é superestimada.",
    "alternativa3": "As estatísticas de acidentes elétricos são menores do que a ocorrência real.",
    "alternativa4": "O planejamento de ações preventivas se torna mais eficaz.",
    "alternativa5": "Há um aumento na notificação de acidentes de outras naturezas.",
    "respostaCorreta": "C",
    "gabaritoComentado": "O excerto afirma que a subnotificação (cerca de 80%) significa que os números reportados não representam o universo total, implicando que as estatísticas são inferiores à quantidade real de acidentes elétricos."
  },
  {
    "tema": "NR 10",
    "pergunta": "Além de comprovar a qualificação, habilitação, capacitação e autorização, o excerto estabelece que a documentação referente aos ______ realizados pelos trabalhadores também deve constar no Prontuário da NR 10.",
    "alternativa1": "Exames de saúde periódicos.",
    "alternativa2": "Diálogos diários de segurança.",
    "alternativa3": "Treinamentos.",
    "alternativa4": "Avaliações de desempenho.",
    "alternativa5": "Procedimentos operacionais.",
    "respostaCorreta": "C",
    "gabaritoComentado": "O excerto lista a 'documentação comprobatória da qualificação, habilitação, capacitação, autorização dos trabalhadores e dos treinamentos realizados' como parte do Prontuário."
  },
  {
    "tema": "NR 10",
    "pergunta": "A 'Base técnica' é um dos itens que devem constar no conteúdo mínimo dos procedimentos de trabalho, de acordo com o excerto. Qual a finalidade desse item?",
    "alternativa1": "Descrever os equipamentos e ferramentas necessários.",
    "alternativa2": "Fundamentar o procedimento em normas, manuais ou princípios de engenharia aplicáveis.",
    "alternativa3": "Detalhar as etapas práticas da atividade.",
    "alternativa4": "Identificar os perigos e riscos associados.",
    "alternativa5": "Registrar a data de elaboração e revisão do procedimento.",
    "respostaCorreta": "B",
    "gabaritoComentado": "Em procedimentos de trabalho, a 'Base técnica' (excerto) geralmente se refere ao embasamento técnico utilizado para a sua elaboração, como normas técnicas, manuais do fabricante, princípios de segurança, etc."
  },
  {
    "tema": "BIOMECÂNICA E FISIOLOGIA DO TRABALHO",
    "pergunta": "A biomecânica ocupacional, ramo da biomecânica, direciona-se principalmente para qual objetivo no contexto laboral?",
    "alternativa1": "Análise do desempenho de atletas de alto rendimento.",
    "alternativa2": "Estudo das forças atuantes em máquinas industriais pesadas.",
    "alternativa3": "Melhoria do desempenho e prevenção de lesões no ambiente de trabalho.",
    "alternativa4": "Desenvolvimento de próteses e órteses para reabilitação.",
    "alternativa5": "Investigação de acidentes de trânsito relacionados a fatores humanos.",
    "respostaCorreta": "C",
    "gabaritoComentado": "A biomecânica ocupacional aplica os princípios da biomecânica para analisar e otimizar a interação entre trabalhadores e suas atividades, visando a **melhoria do desempenho e a prevenção de lesões** relacionadas ao trabalho."
  },
  {
    "tema": "BIOMECÂNICA E FISIOLOGIA DO TRABALHO",
    "pergunta": "A cinética, um dos ramos da biomecânica, dedica-se ao estudo de:",
    "alternativa1": "Os tipos de movimento realizados pelo corpo humano.",
    "alternativa2": "As dimensões e características dos postos de trabalho.",
    "alternativa3": "As forças associadas a um movimento, tanto internas quanto externas.",
    "alternativa4": "A amplitude e a frequência dos movimentos repetitivos.",
    "alternativa5": "A percepção do trabalhador sobre o esforço físico despendido.",
    "respostaCorreta": "C",
    "gabaritoComentado": "A **cinética** estuda as **forças associadas a um movimento**, incluindo tanto as forças internas produzidas pelos músculos quanto as forças externas que atuam sobre o corpo."
  },
  {
    "tema": "BIOMECÂNICA E FISIOLOGIA DO TRABALHO",
    "pergunta": "No contexto da fisiologia do trabalho, as pausas predefinidas durante a jornada laboral têm como principal finalidade:",
    "alternativa1": "Aumentar a cadência individual de trabalho.",
    "alternativa2": "Compensar a falta de treinamento adequado.",
    "alternativa3": "Promover a recuperação psicofisiológica dos trabalhadores.",
    "alternativa4": "Reduzir o tempo total dedicado à produção.",
    "alternativa5": "Facilitar a supervisão das atividades laborais.",
    "respostaCorreta": "C",
    "gabaritoComentado": "As pausas predefinidas são importantes medidas de prevenção ergonômica, visando a **recuperação psicofisiológica dos trabalhadores** frente às demandas do trabalho."
  },
  {
    "tema": "BIOMECÂNICA E FISIOLOGIA DO TRABALHO",
    "pergunta": "Em relação ao transporte manual de cargas, qual das condições abaixo é considerada ideal para minimizar a sobrecarga na coluna vertebral?",
    "alternativa1": "Distância vertical da pega da carga ao solo de 50 cm.",
    "alternativa2": "Distância horizontal da pega ao ponto médio dos tornozelos de 40 cm.",
    "alternativa3": "Realizar torções frequentes do tronco durante o levantamento.",
    "alternativa4": "Distância vertical da pega da carga ao solo de 75 cm e distância horizontal da pega ao ponto médio dos tornozelos de 25 cm.",
    "alternativa5": "Manter uma postura assimétrica durante o levantamento da carga.",
    "respostaCorreta": "D",
    "gabaritoComentado": "As condições ideais para o carregamento manual de cargas, visando minimizar a sobrecarga na coluna, incluem uma **distância vertical da pega da carga ao solo de 75 cm** e uma **distância horizontal da pega ao ponto médio dos tornozelos de 25 cm**, sem torções no dorso e sem posturas assimétricas."
  },
  {
    "tema": "BIOMECÂNICA E FISIOLOGIA DO TRABALHO",
    "pergunta": "O trabalho repetitivo é caracterizado por:",
    "alternativa1": "Atividades com movimentos amplos e variados realizados em curtos intervalos.",
    "alternativa2": "Realização de atividades com movimentos muito similares, de forma contínua e por um período considerável de tempo.",
    "alternativa3": "Tarefas que exigem grande esforço físico com baixa frequência de repetição.",
    "alternativa4": "Ciclos de trabalho com duração superior a 30 segundos, onde o componente essencial ocupa menos de 50% do ciclo total.",
    "alternativa5": "Atividades que permitem a alternância constante de posturas e movimentos.",
    "respostaCorreta": "B",
    "gabaritoComentado": "O **trabalho repetitivo** envolve a **realização de atividades com movimentos muito similares, de forma contínua e por um período considerável de tempo**."
  },
  {
    "tema": "BIOMECÂNICA E FISIOLOGIA DO TRABALHO",
    "pergunta": "Qual das seguintes alternativas descreve um indicador biológico de efeito?",
    "alternativa1": "Concentração de uma substância química no ar do ambiente de trabalho.",
    "alternativa2": "Quantidade de um determinado agente tóxico excretado na urina do trabalhador.",
    "alternativa3": "Alteração bioquímica, fisiológica ou outra no organismo associada a um possível dano estabelecido.",
    "alternativa4": "Tempo de exposição de um trabalhador a um agente de risco.",
    "alternativa5": "Utilização de um equipamento de proteção individual específico.",
    "respostaCorreta": "C",
    "gabaritoComentado": "Os **indicadores biológicos de efeito** indicam uma **alteração bioquímica, fisiológica ou outra no organismo** que pode estar associada a um possível dano à saúde."
  },
  {
    "tema": "BIOMECÂNICA E FISIOLOGIA DO TRABALHO",
    "pergunta": "A Análise Ergonômica do Trabalho (AET) deve ser realizada em etapas progressivas, iniciando-se pela:",
    "alternativa1": "Implementação imediata de medidas corretivas.",
    "alternativa2": "Escolha aleatória de postos de trabalho para análise.",
    "alternativa3": "Discussão do problema a ser resolvido e escolha de situações a serem analisadas.",
    "alternativa4": "Aplicação de questionários padronizados aos trabalhadores.",
    "alternativa5": "Medição quantitativa de todos os fatores de risco ergonômicos.",
    "respostaCorreta": "C",
    "gabaritoComentado": "A AET inicia-se pela **discussão do problema a ser resolvido e escolha de situações a serem analisadas**, seguido por um pré-diagnóstico e observações detalhadas."
  },
  {
    "tema": "BIOMECÂNICA E FISIOLOGIA DO TRABALHO",
    "pergunta": "Quais dos seguintes fatores são considerados relevantes na análise da organização do trabalho em uma AET?",
    "alternativa1": "Apenas as características físicas do posto de trabalho.",
    "alternativa2": "Somente o número de acidentes de trabalho registrados.",
    "alternativa3": "Normas de produção, exigências de tempo, ritmo de trabalho e aspectos cognitivos.",
    "alternativa4": "Unicamente a remuneração e as vantagens oferecidas aos trabalhadores.",
    "alternativa5": "Exclusivamente o nível de ruído e a iluminação do ambiente.",
    "respostaCorreta": "C",
    "gabaritoComentado": "A análise da organização do trabalho na AET deve abordar as **normas de produção, as exigências de tempo, o ritmo de trabalho** e os **aspectos cognitivos** que possam comprometer a segurança e a saúde do trabalhador."
  },
  {
    "tema": "BIOMECÂNICA E FISIOLOGIA DO TRABALHO",
    "pergunta": "A Norma Regulamentadora nº 17 (NR 17) prevê que a avaliação das situações de trabalho seja realizada em quantas etapas?",
    "alternativa1": "Apenas uma etapa qualitativa.",
    "alternativa2": "Apenas uma etapa quantitativa.",
    "alternativa3": "Duas etapas: uma inicial (AEP) e uma de aprofundamento (AET).",
    "alternativa4": "Três etapas: preliminar, intermediária e final.",
    "alternativa5": "Uma única etapa que combina métodos qualitativos e quantitativos.",
    "respostaCorreta": "C",
    "gabaritoComentado": "A NR 17 prevê que a avaliação das situações de trabalho seja realizada em **duas etapas**: uma inicial, por meio da **avaliação ergonômica preliminar (AEP)**, e uma etapa de aprofundamento, por meio da **Análise Ergonômica do Trabalho (AET)**."
  },
  {
    "tema": "BIOMECÂNICA E FISIOLOGIA DO TRABALHO",
    "pergunta": "Segundo o texto, qual dos seguintes exemplos NÃO é citado como um fator que afeta a monitorização biológica?",
    "alternativa1": "Atividades com exposição ao agente fora do ambiente de trabalho.",
    "alternativa2": "Higiene pessoal e hábitos de vida e de trabalho.",
    "alternativa3": "Contaminação de produtos colhidos para análise.",
    "alternativa4": "Variações climáticas extremas no local de trabalho.",
    "alternativa5": "Má conservação dos produtos coletados para análise.",
    "respostaCorreta": "D",
    "gabaritoComentado": "Os fatores que afetam a monitorização biológica mencionados no texto incluem atividades com exposição fora do trabalho, higiene pessoal, hábitos, contaminação de amostras, má conservação e variações metodológicas."
  },
  {
    "tema": "BIOMECÂNICA E FISIOLOGIA DO TRABALHO",
    "pergunta": "A ergonomia foi mais divulgada recentemente ao se discutir questões relativas ao trabalho:",
    "alternativa1": "Em atividades agrícolas com uso intensivo de maquinário pesado.",
    "alternativa2": "Assentado frente a telas de computadores, no final do século passado.",
    "alternativa3": "Em ambientes industriais com exposição a agentes químicos.",
    "alternativa4": "No setor de construção civil com movimentação manual de cargas.",
    "alternativa5": "Em atividades de mineração com riscos de acidentes graves.",
    "respostaCorreta": "B",
    "gabaritoComentado": "A ergonomia ganhou maior destaque nos tempos recentes ao se discutir questões **biomecânicas relativas ao trabalho assentado frente a telas de computadores**, no final do século passado."
  },
  {
    "tema": "BIOMECÂNICA E FISIOLOGIA DO TRABALHO",
    "pergunta": "Qual a implicação ética mencionada no texto em relação à utilização de indicadores biológicos de susceptibilidade em candidatos a emprego?",
    "alternativa1": "Aumento dos custos com exames admissionais.",
    "alternativa2": "Dificuldade na interpretação dos resultados dos exames.",
    "alternativa3": "Caracterização de discriminação, pois os ambientes de trabalho devem ser saudáveis para todos, inclusive os susceptíveis.",
    "alternativa4": "Necessidade de consentimento informado do candidato para a realização dos exames.",
    "alternativa5": "Possibilidade de resultados falso-positivos, gerando preocupações desnecessárias.",
    "respostaCorreta": "C",
    "gabaritoComentado": "A utilização de indicadores biológicos de susceptibilidade em candidatos a emprego **caracteriza discriminação**, pois os ambientes de trabalho devem ser saudáveis para todos, inclusive para os indivíduos mais susceptíveis."
  },
  {
    "tema": "BIOMECÂNICA E FISIOLOGIA DO TRABALHO",
    "pergunta": "A implementação de pausas para recuperação psicofisiológica dos trabalhadores, conforme a NR 17, deve:",
    "alternativa1": "Ser acompanhada de um aumento proporcional na cadência individual de trabalho.",
    "alternativa2": "Ser usufruída compulsoriamente nos postos de trabalho.",
    "alternativa3": "Assegurar a saída dos postos de trabalho para satisfação das necessidades fisiológicas, independentemente das pausas.",
    "alternativa4": "Ser definida unilateralmente pelo empregador, sem a necessidade de discussão com os trabalhadores.",
    "alternativa5": "Substituir a necessidade de alternância de atividades.",
    "respostaCorreta": "C",
    "gabaritoComentado": "A NR 17 exige que a introdução de pausas não aumente a cadência individual, que as pausas sejam fora dos postos de trabalho e que seja **assegurada a saída dos postos para necessidades fisiológicas**, independentemente das pausas."
  },
  {
    "tema": "BIOMECÂNICA E FISIOLOGIA DO TRABALHO",
    "pergunta": "Na elaboração da Análise Ergonômica do Trabalho (AET), a coleta de informações detalhadas sobre o maquinário, ferramentas e equipamentos utilizados tem como objetivo:",
    "alternativa1": "Determinar o valor contábil dos ativos da empresa.",
    "alternativa2": "Identificar possíveis disfunções que possam afetar o desempenho e a segurança do trabalhador.",
    "alternativa3": "Elaborar um plano de manutenção preventiva.",
    "alternativa4": "Comparar a tecnologia utilizada com a de outras empresas do setor.",
    "alternativa5": "Atender a requisitos de auditorias financeiras.",
    "respostaCorreta": "B",
    "gabaritoComentado": "A coleta de informações sobre o maquinário, ferramentas e equipamentos visa **identificar possíveis disfunções** que possam impactar o trabalho e a segurança dos trabalhadores."
  },
  {
    "tema": "BIOMECÂNICA E FISIOLOGIA DO TRABALHO",
    "pergunta": "A avaliação de desempenho para efeito de remuneração e vantagens deve considerar:",
    "alternativa1": "Apenas o cumprimento de metas de produção.",
    "alternativa2": "Exclusivamente a assiduidade e a pontualidade do trabalhador.",
    "alternativa3": "As repercussões sobre a saúde dos trabalhadores.",
    "alternativa4": "Unicamente a avaliação subjetiva do superior hierárquico.",
    "alternativa5": "Somente a aplicação de testes de habilidades específicas.",
    "respostaCorreta": "C",
    "gabaritoComentado": "Segundo o item 17.4.4 da NR 17, todo sistema de avaliação de desempenho deve levar em consideração **as repercussões sobre a saúde dos trabalhadores**."
  },
  {
    "tema": "BIOMECÂNICA E FISIOLOGIA DO TRABALHO",
    "pergunta": "No contexto da ergonomia, a adaptação das condições de trabalho às características psicofisiológicas dos trabalhadores é:",
    "alternativa1": "Uma ação voluntária das empresas.",
    "alternativa2": "Recomendada apenas para atividades de alto risco.",
    "alternativa3": "Uma obrigação empresarial, necessária para a aplicação dos princípios da ergonomia.",
    "alternativa4": "Responsabilidade exclusiva dos trabalhadores.",
    "alternativa5": "Aplicável somente em grandes organizações com programas de saúde ocupacional.",
    "respostaCorreta": "C",
    "gabaritoComentado": "A avaliação das situações de trabalho, por meio da AEP ou AET, é uma **obrigação empresarial, necessária para aplicação dos princípios de ergonomia** e adaptação das condições de trabalho às características psicofisiológicas dos trabalhadores."
  },
  {
    "tema": "BIOMECÂNICA E FISIOLOGIA DO TRABALHO",
    "pergunta": "A análise da demanda em uma Análise Ergonômica do Trabalho (AET) permite:",
    "alternativa1": "Definir os métodos de análise sem considerar os objetivos do estudo.",
    "alternativa2": "Ignorar as informações fornecidas pelos trabalhadores.",
    "alternativa3": "Clarificar os objetivos e aspectos a serem estudados na análise ergonômica.",
    "alternativa4": "Restringir o escopo da análise a apenas um posto de trabalho.",
    "alternativa5": "Impedir a participação dos trabalhadores no processo.",
    "respostaCorreta": "C",
    "gabaritoComentado": "A instrução de uma demanda permite **clarificar os objetivos e aspectos a serem estudados na análise ergonômica**."
  },
  {
    "tema": "BIOMECÂNICA E FISIOLOGIA DO TRABALHO",
    "pergunta": "Qual das seguintes situações específicas, segundo a NR 17, requer a realização da Análise Ergonômica do Trabalho (AET)?",
    "alternativa1": "Quando a empresa possui menos de 20 funcionários.",
    "alternativa2": "Quando todos os trabalhadores utilizam equipamentos de proteção individual adequados.",
    "alternativa3": "Quando observada a necessidade de uma avaliação mais aprofundada da situação.",
    "alternativa4": "Quando a avaliação ergonômica preliminar (AEP) não identifica nenhum risco.",
    "alternativa5": "Quando os trabalhadores realizam apenas tarefas administrativas.",
    "respostaCorreta": "C",
    "gabaritoComentado": "A AET deve ser realizada quando **observada a necessidade de uma avaliação mais aprofundada da situação**."
  },
  {
    "tema": "BIOMECÂNICA E FISIOLOGIA DO TRABALHO",
    "pergunta": "Na aplicação dos princípios da ergonomia, os superiores hierárquicos diretos dos trabalhadores devem ser orientados a:",
    "alternativa1": "Impor metas de produção elevadas sem considerar a capacidade dos trabalhadores.",
    "alternativa2": "Restringir a comunicação com os trabalhadores para evitar interrupções na produção.",
    "alternativa3": "Facilitar a compreensão das atribuições e responsabilidades de cada função e manter aberto o diálogo.",
    "alternativa4": "Aplicar punições aos trabalhadores que não atingirem as metas estabelecidas.",
    "alternativa5": "Ignorar as dúvidas dos trabalhadores sobre o exercício de suas atividades.",
    "respostaCorreta": "C",
    "gabaritoComentado": "Os superiores hierárquicos devem ser orientados para **facilitar a compreensão das atribuições e responsabilidades** e **manter aberto o diálogo** com os trabalhadores."
  },
  {
    "tema": "BIOMECÂNICA E FISIOLOGIA DO TRABALHO",
    "pergunta": "A avaliação ergonômica preliminar (AEP) das situações de trabalho pode ser realizada por meio de abordagens:",
    "alternativa1": "Exclusivamente quantitativas.",
    "alternativa2": "Apenas qualitativas.",
    "alternativa3": "Qualitativas, semiquantitativas, quantitativas ou combinação dessas.",
    "alternativa4": "Unicamente por meio da observação direta dos postos de trabalho.",
    "alternativa5": "Somente através da aplicação de questionários aos trabalhadores.",
    "respostaCorreta": "C",
    "gabaritoComentado": "A avaliação ergonômica preliminar pode ser realizada por meio de abordagens **qualitativas, semiquantitativas, quantitativas ou combinação dessas**."
  },
  {
    "tema": "BIOMECÂNICA E FISIOLOGIA DO TRABALHO",
    "pergunta": "Um dos resultados esperados da Análise Ergonômica do Trabalho (AET), especialmente em demandas envolvendo aspectos físicos, é:",
    "alternativa1": "Aumento da produtividade sem alterações nas condições de trabalho.",
    "alternativa2": "Explicitação da inexistência de sobrecargas no sistema osteomuscular.",
    "alternativa3": "Explicitação da existência de sobrecargas estáticas ou dinâmicas do sistema osteomuscular.",
    "alternativa4": "Redução da necessidade de exames médicos ocupacionais.",
    "alternativa5": "Implementação de medidas de controle sem a participação dos trabalhadores.",
    "respostaCorreta": "C",
    "gabaritoComentado": "Um dos resultados esperados da AET é a **explicitação da existência de sobrecargas estáticas ou dinâmicas do sistema osteomuscular**, a ser comparada com os dados de saúde da organização."
  },
  {
    "tema": "BIOMECÂNICA E FISIOLOGIA DO TRABALHO",
    "pergunta": "As recomendações ergonômicas definidas como resultado da AET devem ser:",
    "alternativa1": "Implementadas imediatamente sem validação.",
    "alternativa2": "Mantidas confidenciais para evitar conflitos entre os trabalhadores.",
    "alternativa3": "Relativas a correções e aprimoramento das situações analisadas, registradas em planos claros e validadas pelos trabalhadores envolvidos.",
    "alternativa4": "Focadas apenas em aspectos de organização do trabalho.",
    "alternativa5": "Elaboradas sem considerar os custos de implementação.",
    "respostaCorreta": "C",
    "gabaritoComentado": "As recomendações ergonômicas devem ser **relativas a correções e aprimoramento**, registradas em planos claros e **validadas pelos próprios trabalhadores envolvidos**."
  },
  {
    "tema": "BIOMECÂNICA E FISIOLOGIA DO TRABALHO",
    "pergunta": "No estudo da biomecânica, a análise dos movimentos considerando o tamanho, sequência e cronologia do movimento é denominada:",
    "alternativa1": "Cinética.",
    "alternativa2": "Estática.",
    "alternativa3": "Cinemática.",
    "alternativa4": "Ergonomia.",
    "alternativa5": "Fisiologia.",
    "respostaCorreta": "C",
    "gabaritoComentado": "A **cinemática** estuda os movimentos em si, considerando o **tamanho, sequência e cronologia do movimento**, sem se preocupar com as forças que os causam."
  },
  {
    "tema": "BIOMECÂNICA E FISIOLOGIA DO TRABALHO",
    "pergunta": "A Norma Regulamentadora nº 7 (NR 7) – Programa de Controle Médico de Saúde Ocupacional (PCMSO) – estabelece a obrigatoriedade de:",
    "alternativa1": "Realização apenas de exames admissionais e demissionais.",
    "alternativa2": "Implementação de medidas de controle de riscos ergonômicos sem avaliação médica.",
    "alternativa3": "Planejamento e realização de avaliações clínicas e exames complementares conforme os riscos ocupacionais identificados.",
    "alternativa4": "Utilização de indicadores biológicos de susceptibilidade em todos os exames ocupacionais.",
    "alternativa5": "Afastamento sistemático de trabalhadores expostos a qualquer agente de risco.",
    "respostaCorreta": "C",
    "gabaritoComentado": "O PCMSO estabelece a obrigatoriedade de descrever os possíveis agravos à saúde relacionados aos riscos ocupacionais e conter um **planejamento para a realização tanto das avaliações clínicas quanto dos exames complementares necessários**, conforme os riscos identificados."
  },
  {
    "tema": "BIOMECÂNICA E FISIOLOGIA DO TRABALHO",
    "pergunta": "Os exames médicos ocupacionais admissionais, periódicos, de retorno ao trabalho, de mudança de risco ocupacional e demissionais são:",
    "alternativa1": "Opcionais, dependendo do grau de risco da empresa.",
    "alternativa2": "De responsabilidade exclusiva do trabalhador.",
    "alternativa3": "Obrigatórios, conforme estabelecido na NR 7.",
    "alternativa4": "Realizados apenas em caso de suspeita de doença ocupacional.",
    "alternativa5": "Custeados pelo sindicato da categoria.",
    "respostaCorreta": "C",
    "gabaritoComentado": "A NR 7 estabelece a realização **obrigatória** dos exames médicos ocupacionais: admissionais, periódicos, de retorno ao trabalho, de mudança de risco ocupacional e demissionais."
  },
  {
    "tema": "BIOMECÂNICA E FISIOLOGIA DO TRABALHO",
    "pergunta": "Em caso de afastamento do trabalho por período igual ou superior a 30 dias por motivo de doença ou acidente, o exame médico de retorno ao trabalho deve ser realizado:",
    "alternativa1": "Até 30 dias após o retorno do trabalhador.",
    "alternativa2": "A critério do médico responsável pelo PCMSO.",
    "alternativa3": "Antes que o trabalhador reassuma suas funções.",
    "alternativa4": "Apenas se o afastamento for de origem ocupacional.",
    "alternativa5": "Após 60 dias do retorno, para verificar a readaptação.",
    "respostaCorreta": "C",
    "gabaritoComentado": "No exame de retorno ao trabalho, a avaliação clínica deve ser realizada **antes que o trabalhador reassuma suas funções**, quando ausente por período igual ou superior a 30 dias."
  },
  {
    "tema": "BIOMECÂNICA E FISIOLOGIA DO TRABALHO",
    "pergunta": "O Atestado de Saúde Ocupacional (ASO) emitido pelo médico deve conter informações sobre:",
    "alternativa1": "Apenas os resultados dos exames complementares.",
    "alternativa2": "Somente o histórico médico pessoal do trabalhador.",
    "alternativa3": "Os perigos ou fatores de risco identificados e avaliados no ambiente de trabalho do trabalhador.",
    "alternativa4": "Unicamente a definição de apto ou inapto para a função atual.",
    "alternativa5": "A remuneração e o cargo do trabalhador na empresa.",
    "respostaCorreta": "C",
    "gabaritoComentado": "O ASO deve conter, entre outros itens, a **descrição dos perigos ou fatores de risco identificados e avaliados no ambiente de trabalho** do trabalhador."
  },
  {
    "tema": "BIOMECÂNICA E FISIOLOGIA DO TRABALHO",
    "pergunta": "Constatada a ocorrência ou agravamento de doença relacionada ao trabalho, qual das seguintes ações compete ao empregador após ser informado pelo médico responsável pelo PCMSO?",
    "alternativa1": "Ignorar a informação, pois a responsabilidade é do trabalhador.",
    "alternativa2": "Apenas recomendar ao trabalhador procurar tratamento médico por conta própria.",
    "alternativa3": "Emitir eletronicamente a Comunicação de Acidente do Trabalho (CAT).",
    "alternativa4": "Realizar uma nova avaliação de risco apenas se houver outros casos semelhantes.",
    "alternativa5": "Suspender o contrato de trabalho do empregado imediatamente.",
    "respostaCorreta": "C",
    "gabaritoComentado": "Constatada doença relacionada ao trabalho, o empregador deve, entre outras ações, **emitir eletronicamente a Comunicação de Acidente do Trabalho - CAT**."
  },
  {
    "tema": "BIOMECÂNICA E FISIOLOGIA DO TRABALHO",
    "pergunta": "O relatório analítico anual do PCMSO deve conter, no mínimo:",
    "alternativa1": "Apenas o número de ASOs emitidos.",
    "alternativa2": "Somente a lista de todos os trabalhadores da empresa.",
    "alternativa3": "Estatística de resultados anormais dos exames complementares, categorizados por tipo do exame e por unidade operacional, setor ou função.",
    "alternativa4": "Unicamente o planejamento das ações de saúde para o próximo ano.",
    "alternativa5": "A descrição detalhada dos prontuários médicos individuais.",
    "respostaCorreta": "C",
    "gabaritoComentado": "O relatório analítico anual do PCMSO deve conter, no mínimo, a **estatística de resultados anormais dos exames complementares, categorizados por tipo do exame e por unidade operacional, setor ou função**."
  },
  {
    "tema": "BIOMECÂNICA E FISIOLOGIA DO TRABALHO",
    "pergunta": "A análise de acidentes e doenças relacionadas ao trabalho deve considerar:",
    "alternativa1": "Apenas a versão do trabalhador sobre o ocorrido.",
    "alternativa2": "Somente os dados estatísticos de acidentes da empresa.",
    "alternativa3": "As situações geradoras dos eventos, levando em conta as atividades desenvolvidas, ambiente de trabalho, organização do trabalho e outros fatores relacionados.",
    "alternativa4": "Unicamente o cumprimento das normas de segurança existentes.",
    "alternativa5": "A identificação do culpado pelo acidente.",
    "respostaCorreta": "C",
    "gabaritoComentado": "A análise de acidentes e doenças relacionadas ao trabalho deve considerar **as situações geradoras dos eventos**, levando em conta diversos fatores como atividades, ambiente, organização do trabalho, materiais e processo produtivo."
  },
  {
    "tema": "BIOMECÂNICA E FISIOLOGIA DO TRABALHO",
    "pergunta": "Um dos objetivos da ginástica laboral é:",
    "alternativa1": "Substituir a necessidade de pausas durante a jornada de trabalho.",
    "alternativa2": "Aumentar a carga horária de trabalho sem riscos à saúde.",
    "alternativa3": "Prevenir lesões por esforços repetitivos e distúrbios osteomusculares relacionados ao trabalho (LER/DORT).",
    "alternativa4": "Selecionar os trabalhadores mais aptos para determinadas funções.",
    "alternativa5": "Reduzir os custos com equipamentos de proteção individual.",
    "respostaCorreta": "C",
    "gabaritoComentado": "Embora não explicitamente detalhado nos excertos, o conhecimento geral sobre fisiologia do trabalho e ergonomia indica que a **ginástica laboral** tem como um dos seus principais objetivos a **prevenção de LER/DORT**, atuando na fisiologia muscular e articular."
  },
  {
    "tema": "BIOMECÂNICA E FISIOLOGIA DO TRABALHO",
    "pergunta": "A fadiga muscular no trabalho pode ser influenciada por fatores como:",
    "alternativa1": "Apenas a intensidade do esforço físico realizado.",
    "alternativa2": "Somente a duração da jornada de trabalho.",
    "alternativa3": "Intensidade e duração do esforço, pausas inadequadas, condições ambientais e fatores psicossociais.",
    "alternativa4": "Unicamente a idade e o condicionamento físico do trabalhador.",
    "alternativa5": "Apenas a qualidade da alimentação e do sono do trabalhador fora do ambiente laboral.",
    "respostaCorreta": "C",
    "gabaritoComentado": "A **fadiga muscular** é um fenômeno complexo influenciado por diversos fatores, incluindo a **intensidade e duração do esforço**, a **adequação das pausas**, as **condições ambientais** (como temperatura e umidade) e os **fatores psicossociais** (como estresse e ritmo de trabalho)."
  },
  {
    "tema": "BIOMECÂNICA E FISIOLOGIA DO TRABALHO",
    "pergunta": "A manutenção de posturas extremas ou nocivas durante a jornada de trabalho deve ser:",
    "alternativa1": "Incentivada, pois aumenta a eficiência em algumas tarefas.",
    "alternativa2": "Tolerada, desde que o trabalhador utilize equipamentos de proteção individual.",
    "alternativa3": "Evitada, buscando garantir a aplicação dos princípios da ergonomia.",
    "alternativa4": "Aceita, pois alguns postos de trabalho exigem tais condições.",
    "alternativa5": "Compensada com exercícios de alongamento ao final da jornada.",
    "respostaCorreta": "C",
    "gabaritoComentado": "Buscando garantir a aplicação dos princípios da ergonomia, é fundamental **evitar** que os trabalhadores adotem **posturas extremas ou nocivas**."
  },
  {
    "tema": "BIOMECÂNICA E FISIOLOGIA DO TRABALHO",
    "pergunta": "Em relação aos instrumentos e ferramentas manuais, a ergonomia preconiza que:",
    "alternativa1": "O peso da ferramenta seja o principal fator a ser considerado.",
    "alternativa2": "A padronização das ferramentas para todos os trabalhadores é essencial.",
    "alternativa3": "O tipo, formato e textura da empunhadura sejam apropriados à tarefa e ao eventual uso de luvas.",
    "alternativa4": "Quanto mais complexa a ferramenta, maior a eficiência do trabalho.",
    "alternativa5": "O custo da ferramenta seja o fator determinante na sua seleção.",
    "respostaCorreta": "C",
    "gabaritoComentado": "A NR 17 define que a organização deve selecionar as ferramentas manuais para que o **tipo, formato e a textura da empunhadura sejam apropriados à tarefa e ao eventual uso de luvas**."
  }
    // Você pode adicionar mais questões aqui seguindo este formato
];
